import Head from 'next/head'
import Navbar from '../../components/Navbar'
import ArtPage from '../../components/Artwork'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Daffa - Developer & Pixel Artist</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon2.png" />
      </Head>

      <Navbar />
      <ArtPage/>
    </div>
  )
}