import Head from 'next/head'
import Navbar from '../../components/Navbar'
import CodePage from '../../components/Codework'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Daffa - Developer & Pixel Artist</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <CodePage/>
    </div>
  )
}