import { serialize } from 'next-mdx-remote/serialize'
import { MDXRemote } from 'next-mdx-remote'
import fs from 'fs'
import path from 'path'
import matter from 'gray-matter'
import Navbar from '../../components/Navbar'
import Head from 'next/head'
import Image from "next/image";
import readingTime from 'reading-time'

//import SyntaxHighlighter from 'react-syntax-highlighter'

//import { Nav, Button } from '../../components'

//const components = { Nav, Button, SyntaxHighlighter }
const components = {Image}

const PostPage = ({ frontMatter: { title, date, description, tags }, mdxSource, readTime }) => {
  return (
    <div>
        <Head>
            <title>Daffa - Developer & Pixel Artist</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/icon2.png" />
        </Head>
        <Navbar/>
        <div className="max-w-[800px] mx-auto mt-[100px]">
            <div className="mx-6 font-outfit">
            <main>
                <div className='border-b border-b-slate-800 pb-10'>
                    <h1 className='font-bold pb-6'>{title}</h1>
                    <h2 className='text-[#cbd5e0]'>{description}</h2>
                    <h3 className='flex gap-x-3 mt-10 text-yellow-300 justify-between'><div className='flex gap-x-3'>{tags.map((tag, key) => <p className='text-base font-light tracking-wide' key={key}>{tag}</p>)}</div><p className='text-[#e60067] text-base tracking-wide font-light'>{readTime}</p>
                    </h3>
                </div>
                <div className='font-light py-10'>
                    <MDXRemote {...mdxSource} components={components}/>
                </div>
                </main>
            </div>
        </div>
    </div>
  )
}

const getStaticPaths = async () => {
  const files = fs.readdirSync(path.join('posts'))

  const paths = files.map(filename => ({
    params: {
      slug: filename.replace('.mdx', '')
    }
  }))

  return {
    paths,
    fallback: false
  }
}

const getStaticProps = async ({ params: { slug } }) => {
  const markdownWithMeta = fs.readFileSync(path.join('posts',
    slug + '.mdx'), 'utf-8')

  const { data: frontMatter, content } = matter(markdownWithMeta)
  const mdxSource = await serialize(content)

  return {
    props: {
      frontMatter,
      slug,
      mdxSource,
      readTime: readingTime(markdownWithMeta).text
    }
  }
}

export { getStaticProps, getStaticPaths }
export default PostPage